server:
  port: 80
  servlet:
    context-path: /community #项目地址

# 数据源名称
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: qiuyu
      max-active: 15
      min-idle: 5
      removeAbandonedTimeout: 120 # 2分钟

  # 邮箱
  mail:
    #配置邮件消息
    host: smtp.qq.com
    port: 465
    #发送邮件者信箱（也就是你申请POP3/SMTP服务的QQ号）
    username: 2448567284@qq.com
    #申请PO3/SMTP服务时，给我们的邮箱的授权码
    password: jzzyzfazhsardhgh
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail.smtp.ssl.enable: true



  #thymeleaf模板
  thymeleaf:
    cache: false #关闭缓存
    check-template-location: false



  #redis
  redis:
    database: 11 #16个库用哪个
    host: localhost
    port: 6379
    timeout: 5000

  #kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group #根据comsumer.properties配置文件中填写
      enable-auto-commit: true #是否自动提交消费者的偏移量
      auto-commit-interval: 3000 #3秒提交一次
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  #ElasticSearch
  data:
    elasticsearch:
      cluster-name: elastic
      cluster-nodes: localhost:9300

  #Spring线程池配置
  task:
    execution: #TaskExecutionProperties Spring普通线程池
      pool:
        core-size: 5 #核心线程数
        max-size: 15 #最大线程数
        queue-capacity: 100 #队列容量
    scheduling: #TaskSchedulingProperties Spring定时线程池
      pool:
        size: 5 #线程数量

  #QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler3
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5 #线程数




#mybatis-plus
mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml" #加载mapper
  type-aliases-package: "com.qiuyu.bean" #别名
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true  #驼峰映射
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
  global-config:
    db-config:
      id-type: auto #id自增

#logger
logging:
  level:
    com.qiuyu: debug
  file:
    name: community.log


aliyun:
  oss:
    file:
      end-point: "https://oss-cn-hangzhou.aliyuncs.com"
      access-key-id: "LTAI5tQpZ7UhBZHsAE3aDMHu"
      access-key-secret: "ak0qOIRVUJ0Oo7GiDgqjJDoM3kbHDW"
      bucket-name: "qiuyusy-img" #bucket名字
      dir-name: "community"

# caffeine 本地缓存优化热门帖子
caffeine:
  post:
    max-size: 15 #最大页数
    expire-seconds: 180 #过期时间(s)

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "info,caches"

# community
community:
  path:
    domain: http://192.168.222.128:80
    upload-path: /tmp/upload